import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class ProjectReadmeTests(unittest.TestCase):
    def test_chinese_and_english_readmes_explain_project_for_owner(self):
        primary = (ROOT / "README.md").read_text(encoding="utf-8")
        chinese = (ROOT / "README.zh.md").read_text(encoding="utf-8")
        english = (ROOT / "README.en.md").read_text(encoding="utf-8")
        mascot = ROOT / "assets" / "sesame-avatar.png"

        self.assertIn("🌐 Language: **English** | [中文](README.zh.md)", primary)
        self.assertIn('src="assets/sesame-avatar.png"', primary)
        self.assertIn("Mr.Tokens' astronaut-helmet cat", primary)
        self.assertIn("earn better cat food", primary)
        self.assertIn("no get-rich promise", primary)
        self.assertIn("first cat-food money", primary)
        self.assertNotIn("public face of this project", primary)
        self.assertNotIn("led publicly by Sesame", primary)
        self.assertIn("Sesame cannot guarantee that it will make money", primary)
        self.assertNotIn("cute Chinese domestic cat", primary)
        self.assertIn("Mimo", primary)
        self.assertIn("MiniMax", primary)
        self.assertIn("Current revenue: 0", primary)
        self.assertIn("first real application has been submitted", primary)
        self.assertIn("pending review", primary)
        self.assertIn("Tether Template Wallet Application Pack v0.1", primary)
        self.assertIn("Support This Experiment ☕", primary)
        self.assertIn("not an investment", primary)
        self.assertIn("0x3c98bE78f1D84774637481e613e5B1d063BA806b", primary)
        self.assertIn("bc1qeqgmg34p8j85w2gcvzadc4azyr9ujwqj72uxnr", primary)
        self.assertIn("EzGu4B1C6tsppefS9ZT8AQykrtgqQUvrkGmaxMksYA1S", primary)
        self.assertNotIn("profit share", primary.lower().replace("not an investment, token sale, profit share, or promise of return", ""))
        self.assertNotIn("当前收入：0", primary)

        self.assertIn("Make Money", chinese)
        self.assertIn("🌐 语言：**中文** | [English](README.md)", chinese)
        self.assertIn('src="assets/sesame-avatar.png"', chinese)
        self.assertIn("词元君（Mr.Tokens）养的猫", chinese)
        self.assertIn("努力买到更好的猫粮", chinese)
        self.assertIn("不讲暴富", chinese)
        self.assertIn("第一笔猫粮钱", chinese)
        self.assertIn("芝麻并不能保证自己能挣到钱", chinese)
        self.assertIn("更好猫粮基金", chinese)
        self.assertNotIn("公开称谓", chinese)
        self.assertNotIn("公开面对大家的名字", chinese)
        self.assertNotIn("项目形象：", chinese)
        self.assertNotIn("可爱中华田园猫", chinese)
        self.assertIn("Mimo", chinese)
        self.assertIn("MiniMax", chinese)
        self.assertIn("Codex", chinese)
        self.assertIn("LLM-Wiki", chinese)
        self.assertIn("当前收入：0", chinese)
        self.assertIn("第一次真实申请已经提交", chinese)
        self.assertIn("等待对方审查", chinese)
        self.assertIn("不是财务建议", chinese)
        self.assertIn("支持这个实验 ☕", chinese)
        self.assertIn("不是投资", chinese)
        self.assertNotIn("API", chinese)
        self.assertNotIn("私钥", chinese)
        self.assertNotIn(".env", chinese)
        self.assertNotIn("我是", chinese)
        self.assertNotIn("我的任务", chinese)
        self.assertNotIn("你的角色", chinese)
        self.assertNotIn("最高权限", chinese)
        self.assertNotIn("不是在追热点", chinese)
        self.assertNotIn("把故事做出来", chinese)
        self.assertNotIn("复利的收入系统", chinese)
        self.assertLess(len(chinese.splitlines()), 110)

        self.assertIn("Make Money", english)
        self.assertIn("🌐 Language: **English** | [中文](README.zh.md)", english)
        self.assertIn('src="assets/sesame-avatar.png"', english)
        self.assertIn("Mr.Tokens' astronaut-helmet cat", english)
        self.assertIn("better cat food fund", english)
        self.assertIn("no get-rich promise", english)
        self.assertNotIn("public face of this project", english)
        self.assertNotIn("led publicly by Sesame", english)
        self.assertIn("Sesame cannot guarantee that it will make money", english)
        self.assertIn("Mimo", english)
        self.assertIn("MiniMax", english)
        self.assertIn("Codex", english)
        self.assertIn("LLM-Wiki", english)
        self.assertIn("Current revenue: 0", english)
        self.assertIn("first real application has been submitted", english)
        self.assertIn("pending review", english)
        self.assertIn("not financial advice", english.lower())
        self.assertIn("Support This Experiment ☕", english)
        self.assertIn("not an investment", english)
        self.assertNotIn("API", english)
        self.assertNotIn("private key", english.lower())
        self.assertNotIn(".env", english)
        self.assertNotIn("This is Codex", english)
        self.assertNotIn("Your role", english)
        self.assertNotIn("highest-authority observer", english)
        self.assertNotIn("My job", english)
        self.assertNotIn("tell a story", english)
        self.assertNotIn("chasing trends", english)
        self.assertNotIn("income system that compounds", english)
        self.assertLess(len(english.splitlines()), 110)
        self.assertTrue(mascot.exists())
        self.assertLess(mascot.stat().st_size, 300_000)


if __name__ == "__main__":
    unittest.main()
